/**
 * 에러 코드 정의 (도메인별 분류)
 *
 * 형식: E_ZEN_{DOMAIN}_{SPECIFIC_ERROR}
 * 예: E_ZEN_BROWSER_NAV_INVALID_URL
 *
 * 도메인:
 * - BROWSER: 브라우저 네비게이션, 페이지 로드
 * - IPC: 프로세스 간 통신
 * - FILE: 파일 시스템 작업
 * - SECURITY: 보안 정책 위반
 * - VALIDATION: 입력 검증 실패
 * - DATABASE: 데이터베이스 작업
 * - NETWORK: 네트워크 통신
 * - SYSTEM: 시스템 리소스
 * - AUTH: 인증/권한
 * - WINDOW: Electron 윈도우
 * - UNKNOWN: 미분류 에러
 */

export const ERROR_CODES = {
  // ===== Browser Navigation (브라우저 네비게이션) =====
  BROWSER_NAV_INVALID_URL: 'E_ZEN_BROWSER_NAV_INVALID_URL',
  BROWSER_NAV_DNS_FAILED: 'E_ZEN_BROWSER_NAV_DNS_FAILED',
  BROWSER_NAV_TIMEOUT_30S: 'E_ZEN_BROWSER_NAV_TIMEOUT_30S',
  BROWSER_NAV_SSL_ERROR: 'E_ZEN_BROWSER_NAV_SSL_ERROR',
  BROWSER_NAV_CONNECTION_REFUSED: 'E_ZEN_BROWSER_NAV_CONNECTION_REFUSED',
  BROWSER_NAV_HOST_NOT_FOUND: 'E_ZEN_BROWSER_NAV_HOST_NOT_FOUND',
  BROWSER_PAGE_CRASH: 'E_ZEN_BROWSER_PAGE_CRASH',
  BROWSER_LOAD_BLOCKED: 'E_ZEN_BROWSER_LOAD_BLOCKED',

  // ===== IPC Communication (프로세스 간 통신) =====
  IPC_CHANNEL_INVALID: 'E_ZEN_IPC_CHANNEL_INVALID',
  IPC_HANDLER_NOT_FOUND: 'E_ZEN_IPC_HANDLER_NOT_FOUND',
  IPC_TIMEOUT_30S: 'E_ZEN_IPC_TIMEOUT_30S',
  IPC_PERMISSION_DENIED: 'E_ZEN_IPC_PERMISSION_DENIED',
  IPC_RATE_LIMITED: 'E_ZEN_IPC_RATE_LIMITED',
  IPC_INVALID_PAYLOAD: 'E_ZEN_IPC_INVALID_PAYLOAD',
  IPC_HANDLER_ERROR: 'E_ZEN_IPC_HANDLER_ERROR',

  // ===== File Operations (파일 작업) =====
  FILE_NOT_FOUND: 'E_ZEN_FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'E_ZEN_FILE_ACCESS_DENIED',
  FILE_SIZE_EXCEEDS_500MB: 'E_ZEN_FILE_SIZE_EXCEEDS_500MB',
  FILE_PATH_TRAVERSAL: 'E_ZEN_FILE_PATH_TRAVERSAL',
  FILE_READ_ERROR: 'E_ZEN_FILE_READ_ERROR',
  FILE_WRITE_ERROR: 'E_ZEN_FILE_WRITE_ERROR',
  FILE_DELETE_ERROR: 'E_ZEN_FILE_DELETE_ERROR',
  FILE_LOCKED: 'E_ZEN_FILE_LOCKED',
  FILE_INVALID_NAME: 'E_ZEN_FILE_INVALID_NAME',

  // ===== Security Policy (보안 정책) =====
  SECURITY_CSP_VIOLATION: 'E_ZEN_SECURITY_CSP_VIOLATION',
  SECURITY_CORS_BLOCKED: 'E_ZEN_SECURITY_CORS_BLOCKED',
  SECURITY_RATE_LIMITED: 'E_ZEN_SECURITY_RATE_LIMITED',
  SECURITY_UNAUTHORIZED: 'E_ZEN_SECURITY_UNAUTHORIZED',
  SECURITY_FORBIDDEN: 'E_ZEN_SECURITY_FORBIDDEN',
  SECURITY_INVALID_TOKEN: 'E_ZEN_SECURITY_INVALID_TOKEN',
  SECURITY_TOKEN_EXPIRED: 'E_ZEN_SECURITY_TOKEN_EXPIRED',

  // ===== Validation (입력 검증) =====
  VALIDATION_INVALID_URL: 'E_ZEN_VALIDATION_INVALID_URL',
  VALIDATION_INVALID_PATH: 'E_ZEN_VALIDATION_INVALID_PATH',
  VALIDATION_MISSING_FIELD: 'E_ZEN_VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_RANGE: 'E_ZEN_VALIDATION_INVALID_RANGE',
  VALIDATION_INVALID_FORMAT: 'E_ZEN_VALIDATION_INVALID_FORMAT',
  VALIDATION_TYPE_MISMATCH: 'E_ZEN_VALIDATION_TYPE_MISMATCH',

  // ===== Database (데이터베이스) =====
  DB_CONNECTION_FAILED: 'E_ZEN_DB_CONNECTION_FAILED',
  DB_QUERY_ERROR: 'E_ZEN_DB_QUERY_ERROR',
  DB_CONSTRAINT_VIOLATION: 'E_ZEN_DB_CONSTRAINT_VIOLATION',
  DB_NOT_FOUND: 'E_ZEN_DB_NOT_FOUND',
  DB_TRANSACTION_FAILED: 'E_ZEN_DB_TRANSACTION_FAILED',
  DB_MIGRATION_FAILED: 'E_ZEN_DB_MIGRATION_FAILED',

  // ===== Network (네트워크) =====
  NETWORK_TIMEOUT: 'E_ZEN_NETWORK_TIMEOUT',
  NETWORK_CONNECTION_FAILED: 'E_ZEN_NETWORK_CONNECTION_FAILED',
  NETWORK_DNS_FAILED: 'E_ZEN_NETWORK_DNS_FAILED',
  NETWORK_OFFLINE: 'E_ZEN_NETWORK_OFFLINE',
  NETWORK_PROXY_ERROR: 'E_ZEN_NETWORK_PROXY_ERROR',

  // ===== System Resources (시스템 리소스) =====
  SYSTEM_OUT_OF_MEMORY: 'E_ZEN_SYSTEM_OUT_OF_MEMORY',
  SYSTEM_DISK_FULL: 'E_ZEN_SYSTEM_DISK_FULL',
  SYSTEM_PERMISSION_DENIED: 'E_ZEN_SYSTEM_PERMISSION_DENIED',
  SYSTEM_NOT_SUPPORTED: 'E_ZEN_SYSTEM_NOT_SUPPORTED',
  SYSTEM_RESOURCE_EXHAUSTED: 'E_ZEN_SYSTEM_RESOURCE_EXHAUSTED',

  // ===== Authentication & Authorization (인증/권한) =====
  AUTH_INVALID_CREDENTIALS: 'E_ZEN_AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'E_ZEN_AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_LOCKED: 'E_ZEN_AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_INVALID: 'E_ZEN_AUTH_TOKEN_INVALID',
  AUTH_PERMISSION_DENIED: 'E_ZEN_AUTH_PERMISSION_DENIED',
  AUTH_ROLE_REQUIRED: 'E_ZEN_AUTH_ROLE_REQUIRED',

  // ===== Window Management (윈도우 관리) =====
  WINDOW_NOT_FOUND: 'E_ZEN_WINDOW_NOT_FOUND',
  WINDOW_CREATION_FAILED: 'E_ZEN_WINDOW_CREATION_FAILED',
  WINDOW_INVALID_BOUNDS: 'E_ZEN_WINDOW_INVALID_BOUNDS',
  WINDOW_DISPLAY_NOT_FOUND: 'E_ZEN_WINDOW_DISPLAY_NOT_FOUND',

  // ===== Unknown/Misc (미분류/기타) =====
  UNKNOWN: 'E_ZEN_UNKNOWN',
  INTERNAL_ERROR: 'E_ZEN_INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'E_ZEN_NOT_IMPLEMENTED',
  DEPRECATED: 'E_ZEN_DEPRECATED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
